### ISSUE TITLE
/qp doesnt work

### ISSUE THREAD

**Issue by HYPICKLETHING** [bugfroggy/QuickPlay#2]
my Gui doesnt work (1.8.9) and /qp commands arent thee its not a command

**Comment by robere2** [comment]
I've seen this issue before, and I am not sure what's causing it or if it's an issue with my mod or Forge. Try removing the mod from your mod folder, redownloading it, then adding the redownloaded version into your mods folder.

**Comment by robere2** [comment]
Closing this as this issue should be fixed in the latest versions.
