### ISSUE TITLE
Mod isn't enabled on other subdomains

### ISSUE THREAD

**Issue by Snuggle** [bugfroggy/QuickPlay#3]
This mod only seems to work on `mc.hypixel.net`. I usually connect using `❤.hypixel.net` or `snuggle.hypixel.net`. You should really match for all subdomains. c:

*.hypixel.net
anything.hypixel.net

**Debug Information:**
MC Version: `1.8.9`
MCP Version: `9.19`
Forge Version: `11.15.1.1722`
Mod Version: `quickplay 1.2.2 (1.8.9-1.8.9)`
Connected To: `❤.hypixel.net`
Is Enabled: false (R)
OS: Arch Linux - 4.13.9
Java Version: 1.8.0

**Comment by robere2** [comment]
The current regex for valid IPs in v1.2.2 is:
`^(?:(?:(?:\w+\.)?hypixel\.net)|(?:209\.222\.115\.\d{1,3}))(?::\d{1,5})?$`
This means the IP `snuggle.hypixel.net` should be valid, but `❤.hypixel.net` is not, as it is not a word character.

In v2.0 I plan on bettering the system to not entirely depend on the IP connected with but also the scoreboard and available server commands. It's recommended you just use the normal IP for now.

**Comment by robere2** [comment]
This is resolved in Quickplay 2.0.
https://github.com/bugfroggy/Quickplay2.0
